### ISSUE TITLE
ERROR: WATCH_ FAIL what't worning?

### ISSUE THREAD

**Issue by xxzling** [HiveTracker/firmware#3]
Hello, I am copying this project, but I received such a prompt. It seems that the small board of ts4231 is not included in the hardware. I drew PCB welding separately, connected and downloaded the program, and then output the following content. What is the possible cause of the problem?

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

0

LD

WATCH_ FAIL:1

ERROR: WATCH_ FAIL

**Comment by honnet** [comment]
Hi!
It won't work without the photosensors, and they also need to be exposed to the signals of the lighthouse (V1).

This project is not maintained, but there are alternatives, here is an open one:

- https://www.bitcraze.io/products/lighthouse-positioning-deck/
- https://github.com/bitcraze/

Also, you might appreciate this community:
https://discord.gg/FwyFu28k

Good luck!

**Comment by honnet** [comment]
Closing issue.

**Comment by xxzling** [comment]
Thanks for your help,However, I still want to continue to try this project. I have V1 lighthouse working. How to determine whether it is a hardware or software problem? Because the two pin voltage of my ts4321 small board photoelectric sensor is negative according to the measurement results of the positive and negative poles, I am not sure whether it is normal. Thank you again.

**Comment by honnet** [comment]
It's not an easy project, you should start with simpler.
Here is another alternative:
https://tundra-labs.com/
https://www.tundratracker.com/

**Comment by xxzling** [comment]
You're right. It's difficult to find the current problems. I should know more about the underlying working principle. Thank you for providing ideas
